// Copyright 2026, James Kirkham K4JK
// SPDX-License-Identifier: GPL-3.0-or-later

// Gardner clock recovery + 4-level C4FM slicer (Phase 1 FM) and
// complex Gardner + differential decode (Phase 2 H-DQPSK and Phase 1 CQPSK)
//
// One thread per channel; the timing loop is sequential within each thread
// (Gardner feedback is causal).  All three modes are handled in the same
// kernel, selected per-channel via d_channel_mode:
//   1 = Phase 1 FM/FSK4  — real Gardner on d_fm_filtered, C4FM slicer
//   2 = Phase 2 H-DQPSK  — complex Gardner on d_s2_output, dqpsk slicer, sps=6000
//   3 = Phase 1 CQPSK    — complex Gardner on d_s2_output, dqpsk slicer, sps=4800
//
// Grid: ceil(M/512)   Block: 512
//
// --- Phase 1 FM (mode 1, C4FM, FDMA) ---
// Input:  d_fm  [in_steps * M], step-major — FM demod output (radians/sample)
// Why Gardner over M&M:
//   Gardner error = (x[n-1] - x[n+1]) × x_mid[n]
//   The DC carrier offset cancels in the difference (x[n-1] - x[n+1]) because
//   both symbol samples carry the same DC component.  M&M requires slicer
//   decisions for its error term; wrong decisions (from unremoved DC offset)
//   drive the timing loop in the wrong direction — a vicious cycle during
//   re-acquisition after a control-channel timeout.
//
// Cross-block state (Phase 1):
//   d_mm_mu          — fractional timing carry-over (may be in (-1, sps))
//   d_mm_omega       — per-channel samples-per-symbol estimate
//   d_mm_fm_last     — last MM_HIST FM samples of the previous block:
//                        [k]=fm(-1), [M+k]=fm(-2), ..., [7M+k]=fm(-8)
//   d_mm_last_interp — previous raw symbol sample (Gardner error numerator)
//   d_mm_dc_est      — IIR DC carrier estimate (for slicer only, not timing)
//   d_mm_fast_ctr    — fast-gain countdown (symbols remaining in acquisition)
//
// Why MM_HIST=12 samples of FM/IQ history:
//   8-tap MMSE FIR requires samples x[i0-3] through x[i0+4].
//   Break condition: i0+4 >= in_steps → last strobe at i0 ≤ 75.
//   Carry-out = mu_after_last_strobe − in_steps (same formula for all modes).
//   The carry oscillates between ~−1.4 and ~−3.6 from alternating 30/31 strobings
//   per 80-sample batch (since 80/2.604 ≈ 30.72).  During fast-gain acquisition
//   (gain_mu=0.05, up to 31 symbols), Gardner gain can push carry an additional
//   31×0.05=1.55 samples negative, so the practical minimum is ~−5.1.
//   The midpoint FIR at carry μ needs iq_hist up to index floor(μ−sps/2)−3:
//     at μ=−5.1: floor(−5.1−1.302)−3 = −10 → hi=9, needs MM_HIST≥10.
//   MM_HIST=12 provides safety margin: covers carry as low as −7.7.
//
// --- Phase 2 (H-DQPSK, TDMA) and Phase 1 CQPSK (mode 3) ---
// Input:  d_s2  [in_steps * M], step-major — complex IQ from stage-2 output
//
// Gardner timing recovery on complex IQ samples, then differential decode at
// the symbol level (multiply consecutive complex symbols: diff = curr×conj(prev))
// → take arg → ±π/4 or ±3π/4.  Rescale by 4/π → ±1 or ±3 → dibit (same
// encoding as Phase 1, matching fsk4_slicer_fb in the non-CUDA cqpsk path).
//
// Phase 1 C4FM and Phase 2 H-DQPSK produce identical differential phase
// transitions (±π/4 and ±3π/4) — the only difference is the symbol rate:
//   Phase 1 CQPSK: 4800 baud → sps = 12500/4800 = 2.6042
//   Phase 2 TDMA:  6000 baud → sps = 12500/6000 = 2.0833
//
// Cross-block state (Phase 2 and Phase 1 CQPSK):
//   d_mm_mu, d_mm_omega, d_mm_fast_ctr — shared with Phase 1 (per-channel arrays)
//   d_mm_dc_est      — IIR DC estimate of decoded phase (removes carrier offset bias)
//   d_p2_iq_last     — last MM_HIST complex IQ samples [MM_HIST*M]
//   d_p2_last_sym    — previous decoded complex symbol [M] for differential decode
//
// P25 C4FM deviation (Phase 1):
//   Outer symbols ±3: ±1800 Hz → ±1800·2π/12500 = ±0.9048 rad/samp
//   Inner symbols ±1:  ±600 Hz →  ±600·2π/12500 = ±0.3016 rad/samp
//   Decision threshold (midpoint):  (0.9048+0.3016)/2 = 0.6032 rad/samp
//
// P25 H-DQPSK symbol transitions (Phase 2, after differential decode):
//   Outer: ±3π/4 (±2.3562 rad) → rescaled to ±3.0
//   Inner: ±π/4  (±0.7854 rad) → rescaled to ±1.0
//   Decision threshold: ±π/2 (±1.5708 rad) → ±2.0 after rescale
//
// Dibit encoding (P25 standard, both phases):
//   Symbol +3 → dibit 01 (1)
//   Symbol +1 → dibit 00 (0)
//   Symbol -1 → dibit 10 (2)
//   Symbol -3 → dibit 11 (3)

#include "symbol_recovery.h"
#include <cstdio>
#include <cstring>

// ---------------------------------------------------------------------------
// GNU Radio MMSE FIR interpolator table (verbatim from
//   /usr/include/gnuradio/filter/interpolator_taps.h, generated by
//   gen_interpolator_taps — do not edit by hand).
//
// Table: taps[NSTEPS+1][NTAPS] = taps[129][8].
// Columns are labelled -4 -3 -2 -1 0 +1 +2 +3 (offsets from output position).
//
// Calling convention: to interpolate at position mu = i0 + frac
//   (i0 = floor(mu), frac = mu - i0):
//
//   imu = round((1-frac) * NSTEPS)         ← NOTE: 1-frac, not frac
//   output = Σ_{t=0}^{7} taps[imu][t] × x[i0-3+t]
//
// Why (1-frac):  at frac=0, imu=128, tap[128][3]=1 → x[i0] (correct).
//                at frac=1, imu=0,   tap[0][4]=1   → x[i0+1] (correct).
//                Using frac directly gives x[i0+1] at frac=0 — 1 sample late.
//
// The 8 samples span x[i0-3] through x[i0+4]; break when i0+4 >= in_steps.
// ---------------------------------------------------------------------------
namespace gr_interp {
#include <gnuradio/filter/interpolator_taps.h>
}

// ---------------------------------------------------------------------------
// MMSE FIR table in GPU constant memory (129×8 floats = 4128 bytes).
// Uploaded once from gr_interp::taps in mm_alloc().
// ---------------------------------------------------------------------------
// MM_HIST defined in symbol_recovery.h (constexpr, shared with cuda_channelizer_impl.cc)
#define MM_NSTEPS 128   // must equal gr_interp::NSTEPS
#define MM_NTAPS    8   // must equal gr_interp::NTAPS

__constant__ float c_mmse_taps[MM_NSTEPS + 1][MM_NTAPS];

#define CUDA_CHECK_MM(call)                                                   \
    do {                                                                      \
        cudaError_t _e = (call);                                              \
        if (_e != cudaSuccess) {                                              \
            fprintf(stderr, "CUDA error %s:%d  %s\n",                        \
                    __FILE__, __LINE__, cudaGetErrorString(_e));              \
            return false;                                                     \
        }                                                                     \
    } while (0)

// ---------------------------------------------------------------------------
// Device helpers
// ---------------------------------------------------------------------------

// 4-level slicer for P25 Phase 1 C4FM (FM-demod output in rad/samp).
static __device__ float decide_c4fm(float y)
{
    const float T = 0.6032f;
    if (y >  T) return +3.0f;
    if (y > 0.0f) return +1.0f;
    if (y > -T) return -1.0f;
    return -3.0f;
}

// Map symbol value (±1.0 or ±3.0) to dibit (0-3).
static __device__ int8_t symbol_to_dibit(float d)
{
    if (d > +2.0f) return 1;   // +3 → 01
    if (d > 0.0f)  return 0;   // +1 → 00
    if (d > -2.0f) return 2;   // -1 → 10
    return 3;                   // -3 → 11
}

// 4th-order Costas loop bandwidth for Phase 1 CQPSK (mode 3).
// Matches digital.costas_loop_cc(alpha=0.008, order=4) in the CPU reference.
// COSTAS_BETA follows the standard second-order PLL critically-damped relation: β = α²/4.
static constexpr float COSTAS_ALPHA    = 0.008f;
static constexpr float COSTAS_BETA     = COSTAS_ALPHA * COSTAS_ALPHA / 4.0f;
static constexpr float COSTAS_MAX_FREQ = 0.01f;   // [rad/symbol] frequency integrator clamp

// Phase slip detection window.  The signed slip counter increments on outer
// symbols (|phase_dc| > π/2) and decrements on inner symbols (|phase_dc| < π/2).
// When it saturates at ±COSTAS_SLIP_WIN the Costas phase is snapped by ∓π/2.
static constexpr int   COSTAS_SLIP_WIN = 50;

// 4-level slicer for P25 Phase 2 H-DQPSK.
// Input y = differential phase (radians), DC-corrected.
// Rescales by 4/π so ±π/4 → ±1.0 and ±3π/4 → ±3.0, then applies the same
// symbol_to_dibit thresholds — matching the non-CUDA cqpsk path:
//   diff_phasor_cc → complex_to_arg → ×(4/π) → fsk4_slicer_fb([-2,0,2,4])
static __device__ int8_t dqpsk_to_dibit(float y)
{
    float v = y * (4.0f / 3.14159265358979f);
    if (v > 2.0f)  return 1;   // +3π/4 → dibit 01
    if (v > 0.0f)  return 0;   // +π/4  → dibit 00
    if (v > -2.0f) return 2;   // -π/4  → dibit 10
    return 3;                   // -3π/4 → dibit 11
}

// ---------------------------------------------------------------------------
// Kernel
// ---------------------------------------------------------------------------

// C = fft_size (channel count = num_phases * fft_oversample)
__global__ void mm_recovery_kernel(
    const float*        __restrict__ d_fm,        // [in_steps * C] Phase 1 FM demod, step-major
    const cufftComplex* __restrict__ d_s2,        // [in_steps * C] Phase 2 complex IQ, step-major
    float*   d_mu,                                // [C] fractional timing phase (in/out)
    float*   d_omega,                             // [C] samples-per-symbol estimate (in/out)
    float*   d_fm_last,                           // [MM_HIST*C] Phase 1: last MM_HIST FM samples (in/out)
    cufftComplex* d_iq_last,                      // [MM_HIST*C] Phase 2: last MM_HIST IQ samples (in/out)
    float*   d_last_sym,                          // [C] Phase 1: previous raw symbol value (in/out)
    cufftComplex* d_last_sym_c,                   // [C] Phase 2: previous decoded complex symbol (in/out)
    float*   d_dc_est,                            // [C] IIR DC estimate (in/out)
    const int8_t* __restrict__ d_channel_mode,   // [C]: 1=Phase1 FM/FSK4, 2=Phase2 H-DQPSK, 3=Phase1 CQPSK
    const int8_t* __restrict__ d_in_warmup,      // [C]: 1=coasting (S2 warmup), 0=normal
    float*   d_symbols,                           // [MM_MAX_SYM * C] output symbol values (Phase 1 debug)
    int8_t*  d_dibits,                            // [MM_MAX_SYM * C] output dibits
    int32_t* d_sym_count,                         // [C] output: valid symbols per channel
    int32_t* d_fast_ctr,                          // [C] fast-gain countdown (in/out)
    const float* __restrict__ d_derot_step,       // [C] per-sample IQ derotation phase [rad/sample] (0 = off)
    float*                    d_derot_acc,        // [C] accumulated derotation phase at batch start (in/out)
    float*                    d_costas_phase,     // [C] Costas loop phase accumulator (mode 3 only, in/out)
    float*                    d_costas_freq,      // [C] Costas frequency integrator (mode 3 only, in/out)
    int32_t*                  d_costas_slip_ctr,  // [C] signed slip-detection counter (mode 3 only, in/out)
    int debug,
    int C, int in_steps,
    float sps_p1, float sps_p2)                   // nominal sps for each mode
{
    const int k = static_cast<int>(blockIdx.x) * static_cast<int>(blockDim.x)
                + static_cast<int>(threadIdx.x);
    if (k >= C) return;

    const int8_t mode = d_channel_mode[k];

    // Per-channel omega clamp (±0.2% of nominal sps, matches gardner_cc d_omega_rel=0.002)
    const float sps_nom = (mode == 2) ? sps_p2 : sps_p1;

    // During S2 filter warmup the padded buffer history is zeros → near-zero IQ
    // → undefined FM (±π spikes).  Coast with frozen mu rather than letting
    // the timing loop corrupt its state on garbage input.
    if (d_in_warmup[k]) {
        d_mu[k]        = sps_nom * 0.5f;   // hold at reset position
        d_sym_count[k] = 0;
        return;   // omega, fm_last, dc_est, fast_ctr all preserved unchanged
    }

    float mu        = d_mu[k];
    float omega     = d_omega[k];
    float dc_est    = d_dc_est[k];
    int32_t fast_ctr = d_fast_ctr[k];

    const float sps_min = sps_nom * 0.998f;
    const float sps_max = sps_nom * 1.002f;

    // Two-phase gains: fast during initial acquisition, slow for steady-state jitter.
    const float gain_mu    = (fast_ctr > 0) ? 0.05f    : 0.025f;
    const float gain_omega = (fast_ctr > 0) ? 0.00025f : 0.0000625f;
    const float dc_alpha   = (fast_ctr > 0) ? 0.9f     : 0.995f;

    int n_sym = 0;

    // -----------------------------------------------------------------------
    // Phase 1 FM (mode 1): real Gardner on FM demod output
    // -----------------------------------------------------------------------
    if (mode == 1) {
        // Load MM_HIST cross-batch FM samples into registers.
        // fm_hist[h] = fm(-(h+1)) for h = 0..MM_HIST-1
        float fm_hist[MM_HIST];
        for (int h = 0; h < MM_HIST; h++)
            fm_hist[h] = d_fm_last[h * C + k];

        float last_sym = d_last_sym[k];

        // Unified FM sample accessor: positive indices from current batch,
        // negative indices from cross-batch history.
        auto get_fm = [&](int i) -> float {
            if (i >= 0) return d_fm[i * C + k];
            const int hi = -i - 1;   // -1→0, -2→1, ..., -MM_HIST→MM_HIST-1
            return (hi < MM_HIST) ? fm_hist[hi] : 0.0f;
        };

        // GNU Radio MMSE FIR interpolation at fractional position fmu.
        // Uses imu = round((1-frac)*NSTEPS) so that imu=NSTEPS → x[i0] at frac=0.
        // Requires get_fm(i0-3) through get_fm(i0+4).
        auto interp_fm = [&](float fmu) -> float {
            const int   i0   = static_cast<int>(floorf(fmu));
            const float frac = fmu - static_cast<float>(i0);
            const int   imu  = min(MM_NSTEPS,
                                   static_cast<int>((1.0f - frac) * MM_NSTEPS + 0.5f));
            float out = 0.0f;
            for (int t = 0; t < MM_NTAPS; t++)
                out += c_mmse_taps[imu][t] * get_fm(i0 - 3 + t);
            return out;
        };

        while (n_sym < MM_MAX_SYM) {
            // Break when MMSE FIR would need samples beyond the current batch.
            // The +4 term is the furthest positive offset in the 8-tap window
            // (base i0-3, taps 0..7 → samples i0-3 .. i0+4).
            int i0 = static_cast<int>(floorf(mu));
            if (i0 + 4 >= in_steps) break;

            float curr_sym = interp_fm(mu);
            float mid_samp = interp_fm(mu - omega * 0.5f);

            float e = (last_sym - curr_sym) * mid_samp;
            if (e >  1.0f) e =  1.0f;
            if (e < -1.0f) e = -1.0f;

            omega += gain_omega * e;
            if (omega < sps_min) omega = sps_min;
            if (omega > sps_max) omega = sps_max;

            mu      += omega + gain_mu * e;
            last_sym = curr_sym;

            dc_est += (1.0f - dc_alpha) * (curr_sym - dc_est);
            float y_dc = curr_sym - dc_est;

            float d = decide_c4fm(y_dc);
            d_symbols[n_sym * C + k] = y_dc;
            d_dibits [n_sym * C + k] = symbol_to_dibit(d);
            n_sym++;
        }

        // Save MM_HIST most-recent FM samples as history for the next batch.
        // in_steps >= MM_HIST is guaranteed (batch is 80 samples, MM_HIST=8).
        for (int h = 0; h < MM_HIST; h++)
            d_fm_last[h * C + k] = d_fm[(in_steps - 1 - h) * C + k];
        d_last_sym[k] = last_sym;

    // -----------------------------------------------------------------------
    // Phase 2 H-DQPSK (mode 2) and Phase 1 CQPSK (mode 3):
    // complex Gardner on IQ, differential decode at symbol level.
    // sps_nom is already set per mode (sps_p2 for mode 2, sps_p1 for mode 3).
    // -----------------------------------------------------------------------
    } else {
        // Load MM_HIST cross-batch complex IQ samples.
        // These are stored ALREADY DEROTATED so negative-index lookups need no rotation.
        cufftComplex iq_hist[MM_HIST];
        for (int h = 0; h < MM_HIST; h++)
            iq_hist[h] = d_iq_last[h * C + k];

        cufftComplex last_sym_c = d_last_sym_c[k];

        // Raw IQ tracker for Gardner (mode 3 only) — carries the un-normalized
        // previous symbol.  Initialized from last_sym_c; first-batch error is
        // slightly wrong but clamped to ±1 and corrected quickly.
        cufftComplex last_sym_raw = last_sym_c;

        // Costas loop state (mode 3 only; 0 for mode 2).
        float   costas_phase = (mode == 3) ? d_costas_phase[k]    : 0.0f;
        float   costas_freq  = (mode == 3) ? d_costas_freq[k]     : 0.0f;
        int32_t slip_ctr     = (mode == 3) ? d_costas_slip_ctr[k] : 0;

        // Per-bin carrier derotation: removes residual Δf = channel_freq - bin_center.
        // derot_acc is the accumulated phase at the start of this batch.
        // Positive-index samples (current batch) are rotated on-the-fly.
        // Negative-index samples come from iq_hist (already derotated in previous batch).
        const float derot_step = d_derot_step[k];
        const float derot_acc  = d_derot_acc[k];

        auto get_iq = [&](int i) -> cufftComplex {
            if (i >= 0) {
                cufftComplex x = d_s2[i * C + k];
                if (derot_step != 0.0f) {
                    float phi = derot_acc + i * derot_step;
                    float c, s;
                    __sincosf(phi, &s, &c);
                    return {x.x * c - x.y * s, x.x * s + x.y * c};
                }
                return x;
            }
            const int hi = -i - 1;
            return (hi < MM_HIST) ? iq_hist[hi] : cufftComplex{0.0f, 0.0f};
        };

        // GNU Radio MMSE FIR complex interpolation (same imu convention as Phase 1).
        auto interp_iq = [&](float fmu) -> cufftComplex {
            const int   i0   = static_cast<int>(floorf(fmu));
            const float frac = fmu - static_cast<float>(i0);
            const int   imu  = min(MM_NSTEPS,
                                   static_cast<int>((1.0f - frac) * MM_NSTEPS + 0.5f));
            cufftComplex out = {0.0f, 0.0f};
            for (int t = 0; t < MM_NTAPS; t++) {
                const float      tap = c_mmse_taps[imu][t];
                const cufftComplex s = get_iq(i0 - 3 + t);
                out.x += tap * s.x;
                out.y += tap * s.y;
            }
            return out;
        };

        while (n_sym < MM_MAX_SYM) {
            int i0 = static_cast<int>(floorf(mu));
            if (i0 + 4 >= in_steps) break;

            cufftComplex curr = interp_iq(mu);
            cufftComplex mid  = interp_iq(mu - omega * 0.5f);

            // Mode-specific Gardner timing error:
            //
            // Mode 3 (C4FM/CQPSK): raw IQ — amplitude variation at symbol
            // transitions IS the timing information for constant-envelope FM.
            // Unit normalization destroys the S-curve restoring force and causes
            // Gardner to coast between zero-crossings.  No |mid|² divisor:
            // matches CPU gardner_cc which uses e = Re[(last-curr)×conj(mid)]
            // with no normalization and relies on upstream AGC for scale.
            //
            // Mode 2 (H-DQPSK): unit-normalized Gardner — was working correctly
            // before the raw IQ change, and DQPSK timing information survives
            // normalization (amplitude dips at bandlimited transitions persist).
            cufftComplex curr_for_diff;
            float e;

            if (mode == 3) {
                // Gardner timing error on raw IQ (no normalization — constant-envelope
                // CQPSK timing information lives in the amplitude envelope at transitions;
                // normalization destroys the S-curve restoring force).
                float diff_re = last_sym_raw.x - curr.x;
                float diff_im = last_sym_raw.y - curr.y;
                e = diff_re * mid.x + diff_im * mid.y;
                last_sym_raw = curr;

                // ── Pre-differential Costas rotation ──
                // Rotate curr by -costas_phase so the differential decode sees a
                // phase-coherent signal.  The error is computed from the corrected IQ
                // directly (not from the differential output), giving the loop a true
                // restoring force against absolute constellation rotation.
                float cp, sp;
                __sincosf(-costas_phase, &sp, &cp);
                cufftComplex curr_rot;
                curr_rot.x = curr.x * cp - curr.y * sp;
                curr_rot.y = curr.x * sp + curr.y * cp;

                // Normalize for differential decode and Costas error.
                curr_for_diff = curr_rot;
                float amp = sqrtf(curr_rot.x * curr_rot.x + curr_rot.y * curr_rot.y);
                if (amp > 1e-5f) { curr_for_diff.x /= amp; curr_for_diff.y /= amp; }

                // 4th-order Costas error from corrected normalized IQ.
                // Zeros at ±π/4, ±3π/4 (the QPSK constellation points).
                float sgn_i = (curr_for_diff.x >= 0.0f) ? 1.0f : -1.0f;
                float sgn_q = (curr_for_diff.y >= 0.0f) ? 1.0f : -1.0f;
                float costas_err = sgn_i * curr_for_diff.y - sgn_q * curr_for_diff.x;
                if (costas_err >  1.0f) costas_err =  1.0f;
                if (costas_err < -1.0f) costas_err = -1.0f;

                // Second-order PLL update (β = α²/4 for critical damping).
                costas_freq  += COSTAS_BETA * costas_err;
                if (costas_freq >  COSTAS_MAX_FREQ) costas_freq =  COSTAS_MAX_FREQ;
                if (costas_freq < -COSTAS_MAX_FREQ) costas_freq = -COSTAS_MAX_FREQ;
                costas_phase += costas_freq + COSTAS_ALPHA * costas_err;
                if (costas_phase >  3.14159265f) costas_phase -= 6.28318530f;
                if (costas_phase < -3.14159265f) costas_phase += 6.28318530f;

            } else {
                // Mode 2 H-DQPSK: unit-normalized Gardner, no Costas.
                cufftComplex cn = curr, mn = mid;
                float ca = sqrtf(cn.x * cn.x + cn.y * cn.y);
                if (ca > 1e-5f) { cn.x /= ca; cn.y /= ca; }
                float ma = sqrtf(mn.x * mn.x + mn.y * mn.y);
                if (ma > 1e-5f) { mn.x /= ma; mn.y /= ma; }
                float diff_re = last_sym_c.x - cn.x;
                float diff_im = last_sym_c.y - cn.y;
                e = diff_re * mn.x + diff_im * mn.y;
                curr_for_diff = cn;
            }

            if (e >  1.0f) e =  1.0f;
            if (e < -1.0f) e = -1.0f;

            omega += gain_omega * e;
            if (omega < sps_min) omega = sps_min;
            if (omega > sps_max) omega = sps_max;
            mu += omega + gain_mu * e;

            // Differential decode: curr_for_diff × conj(last_sym_c).
            // For mode 3, curr_for_diff is Costas-corrected; last_sym_c stores
            // the previous Costas-corrected symbol, so the differential is coherent.
            float d_re = curr_for_diff.x * last_sym_c.x + curr_for_diff.y * last_sym_c.y;
            float d_im = curr_for_diff.y * last_sym_c.x - curr_for_diff.x * last_sym_c.y;

            last_sym_c = curr_for_diff;

            // Phase for decision: for mode 3 Costas is already applied pre-differential;
            // for mode 2 there is no Costas — both use the raw differential angle.
            float phase = atan2f(d_im, d_re);

            // DC removal: tracks residual carrier offset after derotation
            // (SDR oscillator error etc.).  For mode 3, suppress dc_est updates
            // during fast-gain: the derotation already removes the static offset,
            // and Gardner startup produces noisy phases that would bias dc_est
            // before timing is locked.  Only enable after fast_ctr expires.
            if (mode != 3 || fast_ctr == 0) {
                dc_est += (1.0f - dc_alpha) * (phase - dc_est);
            }
            float phase_dc = phase - dc_est;

            d_symbols[n_sym * C + k] = phase_dc;
            d_dibits [n_sym * C + k] = dqpsk_to_dibit(phase_dc);
            n_sym++;

            // Phase slip detection (mode 3 only).
            // slip_ctr is a signed saturating counter: outer symbols drive it toward
            // ±COSTAS_SLIP_WIN; inner symbols decay it toward 0.  When it saturates,
            // costas_phase is snapped by ∓π/2 to escape the wrong 90° lock point.
            if (mode == 3) {
                const float HALF_PI = 1.5707963f;
                if (phase_dc > HALF_PI) {
                    slip_ctr = min(slip_ctr + 1,  COSTAS_SLIP_WIN);
                } else if (phase_dc < -HALF_PI) {
                    slip_ctr = max(slip_ctr - 1, -COSTAS_SLIP_WIN);
                } else {
                    // inner symbol: decay counter one step toward 0
                    if      (slip_ctr > 0) slip_ctr--;
                    else if (slip_ctr < 0) slip_ctr++;
                }

                if (slip_ctr >= COSTAS_SLIP_WIN) {
                    // outer symbols dominated with positive phase → slipped +π/2 → correct by -π/2
                    costas_phase -= HALF_PI;
                    if (costas_phase < -3.14159265f) costas_phase += 6.28318530f;
                    slip_ctr = 0;
                    if (debug) printf("Costas slip corrected: slot=%d bin=%d snap=%.4f\n",
                                      0, k, -HALF_PI);
                } else if (slip_ctr <= -COSTAS_SLIP_WIN) {
                    // outer symbols dominated with negative phase → slipped -π/2 → correct by +π/2
                    costas_phase += HALF_PI;
                    if (costas_phase >  3.14159265f) costas_phase -= 6.28318530f;
                    slip_ctr = 0;
                    if (debug) printf("Costas slip corrected: slot=%d bin=%d snap=%.4f\n",
                                      0, k, +HALF_PI);
                }
            }
        }

        // Save MM_HIST most-recent IQ samples as DEROTATED history for next batch.
        // Storing derotated values means negative-index lookups in get_iq() need
        // no further rotation, keeping cross-batch phase continuity correct.
        for (int h = 0; h < MM_HIST; h++) {
            const int s = in_steps - 1 - h;
            cufftComplex x = d_s2[s * C + k];
            if (derot_step != 0.0f) {
                float phi = derot_acc + s * derot_step;
                float c, ss;
                __sincosf(phi, &ss, &c);
                d_iq_last[h * C + k] = {x.x * c - x.y * ss, x.x * ss + x.y * c};
            } else {
                d_iq_last[h * C + k] = x;
            }
        }
        d_last_sym_c[k] = last_sym_c;
        if (mode == 3) {
            d_costas_phase[k]    = costas_phase;
            d_costas_freq[k]     = costas_freq;
            d_costas_slip_ctr[k] = slip_ctr;
        }

        // Advance and wrap the phase accumulator so float precision doesn't drift
        // over thousands of batches.
        if (derot_step != 0.0f) {
            float new_acc = derot_acc + in_steps * derot_step;
            new_acc = fmodf(new_acc, 2.0f * 3.14159265358979f);
            if (new_acc >  3.14159265358979f) new_acc -= 2.0f * 3.14159265358979f;
            if (new_acc < -3.14159265358979f) new_acc += 2.0f * 3.14159265358979f;
            d_derot_acc[k] = new_acc;
        }
    }

    d_mu[k]          = mu - static_cast<float>(in_steps);
    d_omega[k]       = omega;
    d_dc_est[k]      = dc_est;
    d_sym_count[k]   = n_sym;
    d_fast_ctr[k]    = (fast_ctr > n_sym) ? fast_ctr - n_sym : 0;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

bool mm_alloc(ChannelizerState& state)
{
    const int C = state.config.fft_size;

    // Upload GNU Radio MMSE FIR table to GPU constant memory.
    // gr_interp::taps is float[129][8] — same layout as c_mmse_taps.
    static_assert(sizeof(gr_interp::taps) == (MM_NSTEPS + 1) * MM_NTAPS * sizeof(float),
                  "GR table size mismatch — check NSTEPS/NTAPS defines");
    CUDA_CHECK_MM(cudaMemcpyToSymbol(c_mmse_taps, gr_interp::taps,
                                     sizeof(gr_interp::taps)));

    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_mu,
                             static_cast<size_t>(C) * sizeof(float)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_fm_last,
                             static_cast<size_t>(MM_HIST * C) * sizeof(float)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_last_interp,
                             static_cast<size_t>(C) * sizeof(float)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_last_dec,
                             static_cast<size_t>(C) * sizeof(float)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_omega,
                             static_cast<size_t>(C) * sizeof(float)));

    cudaMemset(state.d_mm_mu,          0, static_cast<size_t>(C) * sizeof(float));
    cudaMemset(state.d_mm_fm_last,     0, static_cast<size_t>(MM_HIST * C) * sizeof(float));
    cudaMemset(state.d_mm_last_interp, 0, static_cast<size_t>(C) * sizeof(float));
    cudaMemset(state.d_mm_last_dec,    0, static_cast<size_t>(C) * sizeof(float));
    cudaMemset(state.d_mm_omega,       0, static_cast<size_t>(C) * sizeof(float));

    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_symbols,
                             static_cast<size_t>(MM_MAX_SYM) * C * sizeof(float)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_dibits,
                             static_cast<size_t>(MM_MAX_SYM) * C * sizeof(int8_t)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_sym_count,
                             static_cast<size_t>(C) * sizeof(int32_t)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_dc_est,
                             static_cast<size_t>(C) * sizeof(float)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_fast_ctr,
                             static_cast<size_t>(C) * sizeof(int32_t)));

    cudaMemset(state.d_mm_sym_count, 0, static_cast<size_t>(C) * sizeof(int32_t));
    cudaMemset(state.d_mm_dc_est,    0, static_cast<size_t>(C) * sizeof(float));
    cudaMemset(state.d_mm_fast_ctr,  0, static_cast<size_t>(C) * sizeof(int32_t));

    // Phase 2 state
    CUDA_CHECK_MM(cudaMalloc(&state.d_channel_mode,
                             static_cast<size_t>(C) * sizeof(int8_t)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_p2_iq_last,
                             static_cast<size_t>(MM_HIST * C) * sizeof(cufftComplex)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_p2_last_sym,
                             static_cast<size_t>(C) * sizeof(cufftComplex)));

    cudaMemset(state.d_channel_mode, 1, static_cast<size_t>(C) * sizeof(int8_t));  // default Phase1
    cudaMemset(state.d_p2_iq_last,   0, static_cast<size_t>(MM_HIST * C) * sizeof(cufftComplex));
    cudaMemset(state.d_p2_last_sym,  0, static_cast<size_t>(C) * sizeof(cufftComplex));

    // Warmup gate: 1=coast (S2 history still filling), 0=run normally
    CUDA_CHECK_MM(cudaMalloc(&state.d_mm_in_warmup,
                             static_cast<size_t>(C) * sizeof(int8_t)));
    cudaMemset(state.d_mm_in_warmup, 0, static_cast<size_t>(C) * sizeof(int8_t));

    // IQ derotation state (modes 2 and 3)
    CUDA_CHECK_MM(cudaMalloc(&state.d_iq_derot_step,
                             static_cast<size_t>(C) * sizeof(float)));
    CUDA_CHECK_MM(cudaMalloc(&state.d_iq_derot_acc,
                             static_cast<size_t>(C) * sizeof(float)));
    cudaMemset(state.d_iq_derot_step, 0, static_cast<size_t>(C) * sizeof(float));
    cudaMemset(state.d_iq_derot_acc,  0, static_cast<size_t>(C) * sizeof(float));

    // Costas loop state (mode 3 only; stays zero for modes 1/2)
    CUDA_CHECK_MM(cudaMalloc(&state.d_costas_phase,
                             static_cast<size_t>(C) * sizeof(float)));
    cudaMemset(state.d_costas_phase, 0, static_cast<size_t>(C) * sizeof(float));

    CUDA_CHECK_MM(cudaMalloc(&state.d_costas_freq,
                             static_cast<size_t>(C) * sizeof(float)));
    cudaMemset(state.d_costas_freq, 0, static_cast<size_t>(C) * sizeof(float));

    CUDA_CHECK_MM(cudaMalloc(&state.d_costas_slip_ctr,
                             static_cast<size_t>(C) * sizeof(int32_t)));
    cudaMemset(state.d_costas_slip_ctr, 0, static_cast<size_t>(C) * sizeof(int32_t));

    return true;
}

void mm_process(ChannelizerState& state, int in_steps, int debug)
{
    const int C = state.config.fft_size;

    const float sps_p1 = state.config.channel_bw_hz / 4800.0f;
    const float sps_p2 = state.config.channel_bw_hz / 6000.0f;

    constexpr int CHAN_W = 512;
    mm_recovery_kernel<<<(C + CHAN_W - 1) / CHAN_W, CHAN_W>>>(
        state.d_fm_filtered,
        state.d_s2_output,
        state.d_mm_mu,
        state.d_mm_omega,
        state.d_mm_fm_last,
        state.d_p2_iq_last,
        state.d_mm_last_interp,
        state.d_p2_last_sym,
        state.d_mm_dc_est,
        state.d_channel_mode,
        state.d_mm_in_warmup,
        state.d_mm_symbols,
        state.d_mm_dibits,
        state.d_mm_sym_count,
        state.d_mm_fast_ctr,
        state.d_iq_derot_step,
        state.d_iq_derot_acc,
        state.d_costas_phase,
        state.d_costas_freq,
        state.d_costas_slip_ctr,
        debug,
        C, in_steps, sps_p1, sps_p2);
}

void mm_free(ChannelizerState& state)
{
    if (state.d_mm_mu)          { cudaFree(state.d_mm_mu);          state.d_mm_mu          = nullptr; }
    if (state.d_mm_fm_last)     { cudaFree(state.d_mm_fm_last);     state.d_mm_fm_last     = nullptr; }
    if (state.d_mm_last_interp) { cudaFree(state.d_mm_last_interp); state.d_mm_last_interp = nullptr; }
    if (state.d_mm_last_dec)    { cudaFree(state.d_mm_last_dec);    state.d_mm_last_dec    = nullptr; }
    if (state.d_mm_omega)       { cudaFree(state.d_mm_omega);       state.d_mm_omega       = nullptr; }
    if (state.d_mm_symbols)     { cudaFree(state.d_mm_symbols);     state.d_mm_symbols     = nullptr; }
    if (state.d_mm_dibits)      { cudaFree(state.d_mm_dibits);      state.d_mm_dibits      = nullptr; }
    if (state.d_mm_sym_count)   { cudaFree(state.d_mm_sym_count);   state.d_mm_sym_count   = nullptr; }
    if (state.d_mm_dc_est)      { cudaFree(state.d_mm_dc_est);      state.d_mm_dc_est      = nullptr; }
    if (state.d_mm_fast_ctr)    { cudaFree(state.d_mm_fast_ctr);    state.d_mm_fast_ctr    = nullptr; }
    if (state.d_channel_mode)   { cudaFree(state.d_channel_mode);   state.d_channel_mode   = nullptr; }
    if (state.d_p2_iq_last)     { cudaFree(state.d_p2_iq_last);     state.d_p2_iq_last     = nullptr; }
    if (state.d_p2_last_sym)    { cudaFree(state.d_p2_last_sym);    state.d_p2_last_sym    = nullptr; }
    if (state.d_mm_in_warmup)   { cudaFree(state.d_mm_in_warmup);   state.d_mm_in_warmup   = nullptr; }
    if (state.d_iq_derot_step)  { cudaFree(state.d_iq_derot_step);  state.d_iq_derot_step  = nullptr; }
    if (state.d_iq_derot_acc)   { cudaFree(state.d_iq_derot_acc);   state.d_iq_derot_acc   = nullptr; }
    if (state.d_costas_phase)    { cudaFree(state.d_costas_phase);    state.d_costas_phase    = nullptr; }
    if (state.d_costas_freq)     { cudaFree(state.d_costas_freq);     state.d_costas_freq     = nullptr; }
    if (state.d_costas_slip_ctr) { cudaFree(state.d_costas_slip_ctr); state.d_costas_slip_ctr = nullptr; }
}
